# Generated by Django 3.1.3 on 2020-11-16 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0005_marca'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipos',
            name='marc',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='erp.marca', verbose_name='Categoría'),
            preserve_default=False,
        ),
    ]
